-- AULA 6 - EXEMPLOS

-- EQUIJOIN
-- BUSCAR DEPARTAMENTO E SEUS RESPECTIVOS NOMES DE DEPARTAMENTO

-- FORMA 1

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
        
-- FORMA 2

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E , DEPARTMENTS D
        WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;        
        
-- NON - EQUIJOIN
-- SELECIONAR SOBRENOME, SALARIO E GRADE DAS TABELAS EMPLOYEES E JOB_GRADES
-- ENTRE O MENOR E MAIOR SALARIO

-- FORMA 1

SELECT
    E.LAST_NAME,
    E.SALARY,
    J.GRADE_LEVEL
        FROM EMPLOYEES E JOIN JOB_GRADES J
        ON E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL;
        
-- FORMA 2        
        
SELECT
    E.LAST_NAME,
    E.SALARY,
    J.GRADE_LEVEL
        FROM EMPLOYEES E , JOB_GRADES J
        WHERE E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL;        
        
-- LEFT JOIN
-- TRAZERT TODOS OS FUNCIONARIOS E RESPECTIVOS NOMES DE DEPARTAMENTOS
-- TRARA O SELECIONADO DA TABELA DA ESQUERDA, MESMO QUE O EQUIVALENTE SEJA NULL

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
    
-- TRAZER SOMENTE OS NULL

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        WHERE D.DEPARTMENT_ID IS NULL;

-- RIGHT JOIN
-- TRAZER TODOS OS FUNCIONARIOS E RESPECTIVOS NOMES DE DEPARTAMENTO
-- TRAS MESMO QUE ESSE DEPERTAMENTO NAO TENHO FUNIONARIOS

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
        
-- TRAZER SOMENTE OS NULL

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        WHERE E.DEPARTMENT_ID IS NULL;

-- FULL JOIN
-- TRAZER TODOS OS FUNCIONARIOS E RESPECTIVOS NOMES DE DEPARTAMENTO
-- TRAZ TUDO SELECIONADO NESSAS TABELAS MESMO SE ESTIVER NULL

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- TRAZER SOMENTE O QUE TIVER RESULTADOS NULL EM ABAS TABELAS

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        WHERE E.DEPARTMENT_ID IS NULL;
        
-- SELF JOIN
-- TRAZER NOME E ID DE CARGO DE CADA FUNCIONARIO, COM OS RESPECTIVOS IDS  DE GERENTES E SEUS CARGOS

SELECT
    M.LAST_NAME MANAGER, M.JOB_ID MANAGER_JOB,
    W.LAST_NAME WORKER, W.JOB_ID WORKER_JOB
        FROM EMPLOYEES W JOIN EMPLOYEES M
        ON (M.EMPLOYEE_ID = W.MANAGER_ID);
        -- ORDER BY M.DEPARTMENT_ID, M.JOB_ID;
    
-- CROSS JOIN

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
        FROM EMPLOYEES E CROSS JOIN DEPARTMENTS D;




























        
        
        